### ISSUE TITLE
Release tarball contains incorrect version "0+unknown"

### ISSUE THREAD

**Issue by max-baz** [palantir/python-jsonrpc-server#14]
```
$ curl -sL https://github.com/palantir/python-jsonrpc-server/archive/0.1.0.tar.gz | tar -xzv
$ cd python-jsonrpc-server-0.1.0                                      
$ python -m venv env                                                  
$ . env/bin/activate
$ python setup.py install

$ pip list | rg jsonrpc
python-jsonrpc-server 0+unknown
```

When you repeat the same steps in `develop` branch, you correctly get version `0.1.0`.

This incorrect version breaks `python-language-server`.

```
$ pyls                                                
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-jsonrpc-server 0+unknown (/usr/lib/python3.7/site-packages), Requirement.parse('python-jsonrpc-server>=0.1.0'), {'python-language-server'})
```

**Comment by max-baz** [comment]
Friendly ping @gatesn 😉

**Comment by gatesn** [comment]
The source distributions from Github won’t work since we use versioneer. That took infers the version from git tags.

I can look into publishing source distributions to pypi if we don’t already?

**Comment by max-baz** [comment]
I see, I'll be packaging using the archive from pypi then 👍 However I found a couple of other issues, could you have a look please @gatesn?

Here's the link I used: https://files.pythonhosted.org/packages/source/p/python-jsonrpc-server/python-jsonrpc-server-0.1.0.tar.gz

1. It seems unit tests are broken in that archive. The command `cd test && py.test` works fine both when downloading tarball from Github release or just cloning this repo, but with the archive from pythonhosted.org I'm getting the following error:

```
❯ py.test
============================================================================================================= test session starts ==============================================================================================================
platform linux -- Python 3.7.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /home/maximbaz/private/svn-community/python-jsonrpc-server/trunk/python-jsonrpc-server-0.1.0, inifile:
plugins: cov-2.6.1
collected 0 items / 2 errors                                                                                                                                                                                                                   

==================================================================================================================== ERRORS ====================================================================================================================
____________________________________________________________________________________________________ ERROR collecting test/test_endpoint.py ____________________________________________________________________________________________________
ImportError while importing test module '/home/maximbaz/private/svn-community/python-jsonrpc-server/trunk/python-jsonrpc-server-0.1.0/test/test_endpoint.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_endpoint.py:7: in <module>
    from pyls_jsonrpc import exceptions
E   ModuleNotFoundError: No module named 'pyls_jsonrpc'
____________________________________________________________________________________________________ ERROR collecting test/test_streams.py _____________________________________________________________________________________________________
ImportError while importing test module '/home/maximbaz/private/svn-community/python-jsonrpc-server/trunk/python-jsonrpc-server-0.1.0/test/test_streams.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_streams.py:7: in <module>
    from pyls_jsonrpc.streams import JsonRpcStreamReader, JsonRpcStreamWriter
E   ModuleNotFoundError: No module named 'pyls_jsonrpc'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================================================== 2 error in 0.12 seconds ============================================================================================================
   
```

2. The archive on pythonhosted.org does not contain LICENSE file, which is present in tarball on Github and in the repo itself.

To give you some context, I'm packaging this tool for Arch Linux and both points above are necessary to release the package in the official repo, your assistance is highly appreciated 🙂

**Comment by gatesn** [comment]
License file should be fixed by this PR: https://github.com/palantir/python-jsonrpc-server/pull/15

I can run `tar -xzf python-jsonrpc-server-0.1.0.tar.gz && cd python-jsonrpc-server-0.1.0/ && py.test` successfully? You shouldn't `cd test`

**Comment by max-baz** [comment]
Neat, thanks for the quick follow-up!

It doesn't really matter if I `cd` into `test` or stay in root, in both cases it fails. I think it doesn't fail for you because you have jsonrpc-server globally installed on your box, while in order to package for Arch Linux I'm building in a clean environment, and I'm running tests before installation. Could you please temporarily uninstall `python-jsonrpc-server` from your computer and retry your command?

By the way, out of curiosity, do you manually publish releases on [pypi](https://pypi.org/project/python-jsonrpc-server/) or it happens automatically?

**Comment by gatesn** [comment]
Publishing happens here: https://github.com/palantir/python-jsonrpc-server/blob/develop/scripts/circle/pypi.sh#L17

I checked and running `import pyls_jsonrpc; pyls_jsonrpc.__file__` in an interpreter shows that it's coming from the current directory.

**Comment by max-baz** [comment]
And I confirm this, but still get test failure 😞 I feel we are missing something obvious here...

```
❯ cd /tmp

❯ curl -sL https://files.pythonhosted.org/packages/source/p/python-jsonrpc-server/python-jsonrpc-server-0.1.0.tar.gz | tar -xzv
python-jsonrpc-server-0.1.0/
python-jsonrpc-server-0.1.0/pyls_jsonrpc/
python-jsonrpc-server-0.1.0/pyls_jsonrpc/__init__.py
python-jsonrpc-server-0.1.0/pyls_jsonrpc/dispatchers.py
python-jsonrpc-server-0.1.0/pyls_jsonrpc/endpoint.py
python-jsonrpc-server-0.1.0/pyls_jsonrpc/exceptions.py
python-jsonrpc-server-0.1.0/pyls_jsonrpc/streams.py
python-jsonrpc-server-0.1.0/pyls_jsonrpc/_version.py
python-jsonrpc-server-0.1.0/python_jsonrpc_server.egg-info/
python-jsonrpc-server-0.1.0/python_jsonrpc_server.egg-info/PKG-INFO
python-jsonrpc-server-0.1.0/python_jsonrpc_server.egg-info/SOURCES.txt
python-jsonrpc-server-0.1.0/python_jsonrpc_server.egg-info/dependency_links.txt
python-jsonrpc-server-0.1.0/python_jsonrpc_server.egg-info/requires.txt
python-jsonrpc-server-0.1.0/python_jsonrpc_server.egg-info/top_level.txt
python-jsonrpc-server-0.1.0/test/
python-jsonrpc-server-0.1.0/test/test_endpoint.py
python-jsonrpc-server-0.1.0/test/test_streams.py
python-jsonrpc-server-0.1.0/MANIFEST.in
python-jsonrpc-server-0.1.0/README.rst
python-jsonrpc-server-0.1.0/setup.cfg
python-jsonrpc-server-0.1.0/setup.py
python-jsonrpc-server-0.1.0/versioneer.py
python-jsonrpc-server-0.1.0/PKG-INFO
                                                                                           
❯ cd python-jsonrpc-server-0.1.0                                                                                               
                                                                                           
❯ pip list | grep jsonrpc                                                                                                        
                                                                                           
❯ python               
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyls_jsonrpc; pyls_jsonrpc.__file__
'/tmp/python-jsonrpc-server-0.1.0/pyls_jsonrpc/__init__.py'
>>> 
                                                                                                   
❯ py.test
============================================================================================================= test session starts ==============================================================================================================
platform linux -- Python 3.7.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /tmp/python-jsonrpc-server-0.1.0, inifile:
plugins: cov-2.6.1
collected 0 items / 2 errors                                                                                                                                                                                                                   

==================================================================================================================== ERRORS ====================================================================================================================
____________________________________________________________________________________________________ ERROR collecting test/test_endpoint.py ____________________________________________________________________________________________________
ImportError while importing test module '/tmp/python-jsonrpc-server-0.1.0/test/test_endpoint.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_endpoint.py:7: in <module>
    from pyls_jsonrpc import exceptions
E   ModuleNotFoundError: No module named 'pyls_jsonrpc'
____________________________________________________________________________________________________ ERROR collecting test/test_streams.py _____________________________________________________________________________________________________
ImportError while importing test module '/tmp/python-jsonrpc-server-0.1.0/test/test_streams.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_streams.py:7: in <module>
    from pyls_jsonrpc.streams import JsonRpcStreamReader, JsonRpcStreamWriter
E   ModuleNotFoundError: No module named 'pyls_jsonrpc'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================================================== 2 error in 0.08 seconds ============================================================================================================
                                                                                                         
```

**Comment by max-baz** [comment]
@gatesn I figured out the difference! The pypi archive is missing this file: `test/__init__.py`. As soon as I create it, tests pass! 

Could you please add it too, like the LICENSE? Thanks!

**Comment by gatesn** [comment]
Ah Ha! Good find, will add it and cut a release within the next hour.

**Comment by gatesn** [comment]
Would you mind checking out this branching, running `./setup.py sdist` And verifying the test package is included in the generated source distribution? I’m on mobile at the moment so can’t and don’t want to block you any further

**Comment by max-baz** [comment]
Yeah the branch from your PR produces a correct archive where tests pass! Thanks again for your support, please feel free to close this issue once you release a new archive on pypi.

I think it makes sense if I also update `python-language-server` package to use archive from pypi, quickly looking I can see that LICENSE is already included in the archive, but the `test/__init__.py` is also missing there. Would you please update that one as well?

But I feel that's not it, I created that `__init__.py` file manually and still see some issues (below). Not sure yet if this is a problem on my side yet, but again test run passes when using tarball from Github 🙂 Would you like me to create an issue in `python-language-server` repo or continue this thread?

```
==================================== ERRORS ====================================
____________________ ERROR collecting test/test_document.py ____________________
ImportError while importing test module '/build/python-language-server/src/python-language-server-0.21.5/test/test_document.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_document.py:2: in <module>
    from test.fixtures import DOC_URI, DOC
E   ModuleNotFoundError: No module named 'test.fixtures'
______________________ ERROR collecting test/test_uris.py ______________________
ImportError while importing test module '/build/python-language-server/src/python-language-server-0.21.5/test/test_uris.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_uris.py:2: in <module>
    from test import unix_only, windows_only
E   ImportError: cannot import name 'unix_only' from 'test' (/build/python-language-server/src/python-language-server-0.21.5/test/__init__.py)
```

UPDATE: Just found this bug (https://github.com/palantir/python-language-server/issues/269), we can continue in that thread as well if you like.

**Comment by max-baz** [comment]
I can see that in python-language-server there are also some `.py` files missing in the pypi archive that are present in the github tarball. For example, these are:

```
test/
    __init__.py
    fixtures.py
    conftest.py
```

This is not extensive diff, just what I spotted. I'm almost sure if you add them, python-language-server will also be compiling fine from pypi archive and you would be able to close https://github.com/palantir/python-language-server/issues/269 :)
